import Footer from '@/components/Footer';
import BottomHeader from '@/components/Header/BottomHeader';
import Header from '@/components/Header/Header';
import ModalProvider from '@/providers/ModalProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import ToastProvider from '@/providers/ToastProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToastProvider />
                <ReduxProvider>
                    <ModalProvider />
                    <Header />
                    <BottomHeader />
                    {children}
                </ReduxProvider>
                <Footer />
            </body>
        </html>
    );
}
