name: Build

on:
    push:
        branches:
            - main

    pull_request:
        types: [review_requested]
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '^18.16.0'

            - name: Install dependencies
              run: yarn

            - name: Create bundle
              run: yarn build
